import type { IUserStory } from "../types.ts";

export const stories: IUserStory[] = [
  {
    key: "US-017",
    asA: "jogador",
    iWant: "ver o corredor da masmorra renderizado como um TileMap 2D de tiles de pedra CC0",
    soThat: "o visual do jogo se pareça com a referência do Ruby Warrior em vez do render geométrico atual",
    acceptanceCriteria: [
      "Dado um LevelState com N espaços, quando a cena é exibida, então o TileMap tem N colunas de piso com paredes superior e inferior.",
      "Dado que o jogo inicia, quando o nível 1 carrega, então o corredor de masmorra é visível com tiles de pedra CC0 (não formas geométricas).",
      "Dado qualquer nível, quando a cena renderiza, então 0 chamadas a _draw existem em game_view.gd (render procedural eliminado).",
    ],
    requirementKeys: ["RF-020", "RF-026"],
    priority: "highest",
    storyPoints: 8,
    status: "done",
    assignee: "usuario",
  },
  {
    key: "US-018",
    asA: "jogador",
    iWant: "ver sprites distintos para warrior, sludge, thick sludge, archer, wizard, captive e escada",
    soThat: "eu identifique visualmente cada entidade no corredor sem ler nomes ou formas geométricas",
    acceptanceCriteria: [
      "Dado um LevelState com warrior e sludge, quando o frame é renderizado, então o warrior tem sprite de cavaleiro e o sludge tem sprite de slime — distintos entre si.",
      "Dado a escada no LevelState, quando renderizada, então tem sprite dourado de escada.",
      "Dado um captive no nível, quando renderizado, então tem sprite de cativo acorrentado distinto das unidades de combate.",
    ],
    requirementKeys: ["RF-021", "RF-025"],
    priority: "highest",
    storyPoints: 5,
    status: "done",
    assignee: "usuario",
  },
  {
    key: "US-019",
    asA: "jogador",
    iWant: "ver animações de feedback visual a cada turno (walk, attack, hurt, die, etc.)",
    soThat: "eu entenda o resultado de cada ação da minha lógica pelo feedback visual imediato",
    acceptanceCriteria: [
      "Dado TurnEvent moved, quando a animação executa, então o sprite do warrior desloca para a nova posição com animação walk ≤ 0,4 s.",
      "Dado TurnEvent attacked, quando a animação executa, então o sprite do warrior exibe animação de ataque ≤ 0,4 s.",
      "Dado TurnEvent took_damage, quando a animação executa, então o sprite da unidade atingida exibe animação de hurt ≤ 0,4 s.",
      "Dado TurnEvent enemy_defeated, quando a animação executa, então o sprite do inimigo exibe animação die e é removido da cena.",
      "Dado que animações estão em curso, quando o próximo turno é resolvido, então o TurnResolver retorna em < 16 ms independentemente das animações.",
    ],
    requirementKeys: ["RF-022", "RNF-002"],
    priority: "highest",
    storyPoints: 8,
    status: "done",
    assignee: "usuario",
  },
  {
    key: "US-020",
    asA: "jogador",
    iWant: "ver um HUD com HP (coração), número do turno, descrição do nível e pontuação",
    soThat: "eu acompanhe o estado do jogo em tempo real sem precisar inspecionar logs",
    acceptanceCriteria: [
      "Dado HP = 12 de 20, quando o HUD atualiza, então exibe '♥ 12/20' visível sobre o corredor.",
      "Dado o turno 5, quando o HUD atualiza, então exibe 'Turno: 5' ou equivalente.",
      "Dado que a câmera scrolla em um nível longo, quando o HUD é visível, então permanece fixo na tela (não scrolla com o mundo).",
      "Dado que o warrior avança de nível, quando o HUD atualiza, então exibe a descrição textual do novo nível.",
    ],
    requirementKeys: ["RF-023", "RNF-001"],
    priority: "highest",
    storyPoints: 5,
    status: "done",
    assignee: "usuario",
  },
  {
    key: "US-021",
    asA: "jogador",
    iWant: "que a câmera enquadre o corredor completo em níveis curtos e siga o warrior em níveis longos",
    soThat: "eu sempre veja o warrior e o contexto relevante sem o corredor ficar cortado",
    acceptanceCriteria: [
      "Dado um nível cujo corredor cabe na viewport, quando o nível carrega, então o corredor inteiro é visível sem scroll.",
      "Dado um nível mais longo que a viewport, quando o warrior avança, então a câmera segue com suavização (sem corte brusco).",
      "Dado qualquer nível, quando renderizado, então a escada e o warrior são sempre visíveis no enquadramento atual.",
    ],
    requirementKeys: ["RF-024"],
    priority: "high",
    storyPoints: 3,
    status: "done",
    assignee: "usuario",
  },
  {
    key: "US-022",
    asA: "desenvolvedor",
    iWant: "que a camada de apresentação não importe nem instancie classes do domínio diretamente",
    soThat: "a Clean Architecture (CONV-002) seja preservada e o domínio permaneça independente da engine",
    acceptanceCriteria: [
      "Dado qualquer arquivo .gd de cena, quando faço grep de 'load/preload.*src/domain\\|new.*Domain', então o resultado é 0 ocorrências.",
      "Dado DungeonView recebendo um LevelState, quando renderiza, então acessa apenas a interface pública de LevelState e TurnEvents — sem instanciar Unit, TurnResolver ou outros objetos de domínio.",
    ],
    requirementKeys: ["RNF-001"],
    priority: "highest",
    storyPoints: 2,
    status: "done",
    assignee: "usuario",
  },
];
