import type { ITask } from "../types.ts";

export const tasks: ITask[] = [
  // ── Sprint 1: TileMap + sprites estáticos CC0 ─────────────────────────────

  {
    key: "T-023",
    storyKey: "US-017",
    summary: "Baixar e integrar asset pack CC0 (Kenney Dungeon Pack ou equivalente): tiles de piso e parede em res://assets/tiles/",
    definitionOfDone: "Arquivos PNG/tileset presentes em res://assets/tiles/; AtlasTexture configurada e referenciada em AssetPaths.gd sem string mágica.",
    status: "done",
    dependsOn: [],
    parallel: false,
    assignee: null,
  },
  {
    key: "T-024",
    storyKey: "US-017",
    summary: "Criar DungeonView.tscn com TileMap2D e método refresh_level(state: LevelState) que mapeia células do estado para tiles",
    definitionOfDone: "DungeonView.gd define refresh_level; ao passar um LevelState de 8 espaços, o TileMap exibe 8 células de piso com parede superior/inferior; 0 chamadas a _draw no arquivo.",
    status: "done",
    dependsOn: ["T-023"],
    parallel: false,
    assignee: null,
  },
  {
    key: "T-025",
    storyKey: "US-017",
    summary: "Substituir game_view.gd/_draw pelo DungeonView; remover render procedural por completo",
    definitionOfDone: "game_view.gd ou seu substituto não contém nenhuma função _draw; o nível 1 carrega e exibe o TileMap em execução Godot.",
    status: "done",
    dependsOn: ["T-024"],
    parallel: false,
    assignee: null,
  },
  {
    key: "T-026",
    storyKey: "US-018",
    summary: "Baixar sprites CC0 para warrior, sludge, thick sludge, archer, wizard, captive e escada em res://assets/sprites/",
    definitionOfDone: "Arquivos PNG para cada entidade presentes em res://assets/sprites/ com nomenclatura padronizada conforme AssetPaths.gd.",
    status: "done",
    dependsOn: ["T-023"],
    parallel: true,
    assignee: null,
  },
  {
    key: "T-027",
    storyKey: "US-018",
    summary: "Implementar EntitySpriteRegistry: cria/remove Sprite2D por entity_id a partir do LevelState; posiciona via TileMap.map_to_local()",
    definitionOfDone: "EntitySpriteRegistry cria Sprite2D com o sprite correto para cada tipo de unidade; ao remover unidade do estado, o nó é freed; warrior e sludge têm sprites distintos visíveis em execução.",
    status: "done",
    dependsOn: ["T-024", "T-026"],
    parallel: false,
    assignee: null,
  },
  {
    key: "T-028",
    storyKey: "US-022",
    summary: "Verificar conformidade Clean Architecture: 0 ocorrências de load/preload de src/domain/ em arquivos .gd de cena",
    definitionOfDone: "grep -r 'load.*src/domain\\|preload.*src/domain' src/presentation/ retorna vazio; DungeonView e EntitySpriteRegistry acessam apenas LevelState e TurnEvents via interface Application.",
    status: "done",
    dependsOn: ["T-027"],
    parallel: false,
    assignee: null,
  },

  // ── Sprint 2: Animações de turno + HUD + câmera ───────────────────────────

  {
    key: "T-029",
    storyKey: "US-019",
    summary: "Implementar SpriteFrames/AnimationPlayer por tipo de entidade com animações: idle, walk, attack, hurt, die",
    definitionOfDone: "Cada tipo de entidade tem AnimationPlayer com as 5 animações; duração de cada animação ≤ 0,4 s; as animações são visíveis em execução Godot.",
    status: "done",
    dependsOn: ["T-027"],
    parallel: false,
    assignee: null,
  },
  {
    key: "T-030",
    storyKey: "US-019",
    summary: "Implementar dispatch de TurnEvents → animações em EntitySpriteRegistry; enfileirar e aguardar conclusão antes do próximo turno",
    definitionOfDone: "Para cada TurnEvent (moved, attacked, took_damage, enemy_defeated, rested, rescued), a animação correspondente é disparada; TurnResolver não é chamado enquanto animações estão em curso; resolução < 16 ms verificada por profiler ou log.",
    status: "done",
    dependsOn: ["T-029"],
    parallel: false,
    assignee: null,
  },
  {
    key: "T-031",
    storyKey: "US-020",
    summary: "Criar HudView.tscn como CanvasLayer (layer 1) com Labels de HP, turno, descrição do nível e score",
    definitionOfDone: "HudView exibe '♥ HP/MAX', 'Turno: N', descrição do nível e score; ao scrollar a câmera, o HUD permanece fixo na tela.",
    status: "done",
    dependsOn: ["T-024"],
    parallel: true,
    assignee: null,
  },
  {
    key: "T-032",
    storyKey: "US-020",
    summary: "Conectar HudView ao GameFlowController: chamar update_hud(state, score) após cada turno",
    definitionOfDone: "HP diminui visivelmente no HUD após o warrior ser atingido; score atualiza após evento pontuável; turno incrementa a cada resolução.",
    status: "done",
    dependsOn: ["T-031", "T-030"],
    parallel: false,
    assignee: null,
  },
  {
    key: "T-033",
    storyKey: "US-021",
    summary: "Adicionar Camera2D com position_smoothing à DungeonView; implementar zoom automático para níveis curtos",
    definitionOfDone: "Em nível com corredor ≤ viewport: todo o corredor visível sem scroll. Em nível longo: câmera segue warrior com suavização. Escada sempre visível no enquadramento.",
    status: "done",
    dependsOn: ["T-024"],
    parallel: true,
    assignee: null,
  },
];
