import type { IUserStory } from "../types.ts";

export const stories: IUserStory[] = [
  {
    key: "US-050",
    asA: "jogador",
    iWant: "um menu inicial que me deixa iniciar ou continuar a torre",
    soThat: "eu comece do início ou retome de onde parei",
    acceptanceCriteria: [
      "Dado o jogo aberto, quando vejo o menu, então há iniciar (nível 1) e continuar (nível salvo).",
      "Dado um progresso salvo, quando escolho continuar, então começo no nível alcançado.",
      "Dado nenhum save, quando inicio, então começo no nível 1 sem erro (RNF-051).",
    ],
    requirementKeys: ["RF-050", "RF-055", "RNF-051"],
    priority: "high",
    storyPoints: 5,
    status: "done",
    assignee: "usuario",
  },
  {
    key: "US-051",
    asA: "jogador",
    iWant: "uma tela de transição antes de cada nível com sua descrição e habilidades novas",
    soThat: "eu entenda o que muda e o que aprendo naquele nível",
    acceptanceCriteria: [
      "Dado o início de um nível, quando a transição aparece, então mostra nome/descrição do nível e as habilidades novas introduzidas.",
    ],
    requirementKeys: ["RF-051"],
    priority: "high",
    storyPoints: 5,
    status: "done",
    assignee: "usuario",
  },
  {
    key: "US-052",
    asA: "jogador",
    iWant: "avançar ao vencer, reiniciar o nível e ver meu resultado",
    soThat: "eu progrida pela torre e otimize minha pontuação",
    acceptanceCriteria: [
      "Dado que venci um nível, quando ele termina, então vejo a tela de resultado com pontuação e veredito de ace, e avanço ao próximo.",
      "Dado um nível em andamento, quando escolho reiniciar, então ele recomeça do estado inicial.",
    ],
    requirementKeys: ["RF-052", "RF-053"],
    priority: "high",
    storyPoints: 5,
    status: "done",
    assignee: "usuario",
  },
  {
    key: "US-053",
    asA: "jogador",
    iWant: "uma tela de conclusão com créditos ao terminar a torre",
    soThat: "eu tenha um fechamento da experiência completa",
    acceptanceCriteria: [
      "Dado que venci o último nível, quando a torre termina, então vejo a tela de conclusão e os créditos.",
    ],
    requirementKeys: ["RF-054"],
    priority: "medium",
    storyPoints: 3,
    status: "done",
    assignee: "usuario",
  },
  {
    key: "US-054",
    asA: "jogador",
    iWant: "efeitos sonoros para as ações e eventos do turno",
    soThat: "o jogo dê feedback sonoro do que acontece",
    acceptanceCriteria: [
      "Dado um evento de turno (andar/atacar/dano/descanso/resgate/tiro/vitória/derrota), quando ocorre, então o SFX correspondente toca.",
      "Dado o áudio disparado por evento, quando o turno resolve, então o som não atrasa o ciclo de turno (RNF-052).",
    ],
    requirementKeys: ["RF-056", "RNF-052"],
    priority: "medium",
    storyPoints: 5,
    status: "done",
    assignee: "usuario",
  },
  {
    key: "US-055",
    asA: "jogador",
    iWant: "trilha de fundo e controle de volume, com assets trocáveis",
    soThat: "o jogo seja imersivo e a arte sonora da 42 possa entrar depois",
    acceptanceCriteria: [
      "Dado o jogo em andamento, quando jogo, então há trilha de fundo em loop com controle de volume básico (música/SFX).",
      "Dado os assets de áudio, quando os inspeciono, então são CC0 referenciados de forma trocável sem refactor de lógica (RF-058).",
      "Dado o domínio, quando o verifico, então não há referência a áudio/fluxo de torre dentro de src/domain (RNF-050).",
    ],
    requirementKeys: ["RF-057", "RF-058", "RNF-050"],
    priority: "medium",
    storyPoints: 5,
    status: "done",
    assignee: "usuario",
  },
];
