import type { IUserStory } from "../types.ts";

export const stories: IUserStory[] = [
  {
    key: "US-180",
    asA: "Jogador",
    iWant: "que o mundo seja uma grade 2D (linhas×colunas), com o corredor 1×N como caso R=1",
    soThat: "eu possa programar o warrior em torres Intermediate/Advanced sem que os níveis beginner quebrem",
    acceptanceCriteria: [
      "Dado um LevelState de grade R×C, quando consulto a posição do warrior, então recebo uma coordenada 2D (linha,coluna) válida dentro de [0,R-1]×[0,C-1].",
      "Dado um nível 1×N do beginner, quando ele é carregado no modelo unificado, então é tratado como R=1 e o comportamento de posição/parede é idêntico ao corredor original.",
      "Dado uma coordenada fora de [0,R-1]×[0,C-1], quando o domínio a avalia, então ela é classificada como parede (fora dos limites).",
    ],
    requirementKeys: ["RF-180", "RNF-180"],
    priority: "highest",
    storyPoints: 5,
    status: "done",
    assignee: null,
  },
  {
    key: "US-181",
    asA: "Jogador",
    iWant: "que o warrior aponte e gire entre as 4 direções absolutas (cima/baixo/esquerda/direita)",
    soThat: "eu possa orientá-lo e movê-lo em qualquer eixo do mundo 2D",
    acceptanceCriteria: [
      "Dado um warrior apontando para uma das 4 direções, quando consulto o delta de passo da direção, então recebo o vetor 2D correto (ex.: cima = (-1,0), direita = (0,+1)).",
      "Dado um warrior apontando para o norte, quando executo pivot para leste, então o facing passa a ser leste (giro entre as 4 direções, não só 180°).",
      "Dado o mesmo estado e a mesma direção, quando calculo o passo duas vezes, então o resultado é idêntico (sem RNG, determinístico).",
    ],
    requirementKeys: ["RF-181", "RNF-180"],
    priority: "highest",
    storyPoints: 3,
    status: "done",
    assignee: null,
  },
  {
    key: "US-182",
    asA: "Jogador",
    iWant: "que feel/look/direction_of/direction_of_stairs e o cálculo de passo enxerguem o mundo 2D",
    soThat: "eu possa perceber células em qualquer direção e decidir a lógica do warrior",
    acceptanceCriteria: [
      "Dado um warrior numa grade 2D apontando para uma direção, quando chamo feel/look, então inspeciono a célula 2D naquela direção sem consumir turno.",
      "Dado um alvo (escada/inimigo) em outra linha/coluna, quando chamo direction_of/direction_of_stairs, então recebo a direção 2D que aponta rumo ao alvo.",
      "Dado uma posição e uma direção, quando chamo step_of/position_toward, então recebo a próxima coordenada 2D coerente com o delta da direção.",
    ],
    requirementKeys: ["RF-182", "RNF-180"],
    priority: "highest",
    storyPoints: 5,
    status: "done",
    assignee: null,
  },
  {
    key: "US-183",
    asA: "Jogador",
    iWant: "que a API (warrior_facade/catalog/glossário) exponha as 4 direções sem quebrar meus scripts beginner",
    soThat: "eu reaproveite o que já programei em 1×N e ganhe o movimento 2D de graça",
    acceptanceCriteria: [
      "Dado o catálogo/glossário da API, quando consulto a orientação e o movimento, então as 4 direções e o pivot 4-direções estão descritos e disponíveis.",
      "Dado um script beginner escrito para o corredor 1×N, quando ele roda no mundo unificado (R=1), então funciona sem nenhuma alteração de código do jogador.",
      "Dado o subcaso R=1, quando o warrior anda/sente, então a semântica de forward/backward do beginner é preservada.",
    ],
    requirementKeys: ["RF-183"],
    priority: "high",
    storyPoints: 5,
    status: "done",
    assignee: null,
  },
  {
    key: "US-184",
    asA: "Jogador",
    iWant: "ver e jogar o mundo 2D renderizado (TileMap linhas×colunas, câmera 2 eixos, animações 4 direções) e carregar mapas 2D",
    soThat: "eu experimente as torres Intermediate/Advanced com feedback visual fiel",
    acceptanceCriteria: [
      "Dado um nível de grade R×C, quando a cena é renderizada, então o TileMap exibe linhas×colunas e a câmera acompanha o warrior nos 2 eixos.",
      "Dado o warrior virando/andando nas 4 direções, quando a ação ocorre, então a animação correspondente à direção é exibida.",
      "Dado um layout de nível 2D fornecido ao level_loader, quando ele é carregado, então a grade R×C é montada (e um layout 1×N é lido como R=1).",
    ],
    requirementKeys: ["RF-184"],
    priority: "high",
    storyPoints: 8,
    status: "done",
    assignee: null,
  },
  {
    key: "US-185",
    asA: "Jurado da Jam",
    iWant: "que a evolução 2D não regrida nada das features 001–016 e tenha cobertura de teste real do 2D",
    soThat: "eu confie que o jogo continua íntegro e que o mundo 2D é determinístico e testado",
    acceptanceCriteria: [
      "Dado o repositório após a mudança 2D, quando rodo check.sh, então a suíte de domínio fica 100% verde e as features 001–016 não regridem.",
      "Dado a movimentação 2D, quando inspeciono a cobertura, então há ≥1 teste por direção (4), paredes nas bordas de uma grade R×C e sentidos 2D cobertos.",
      "Dado o caso R=1 (beginner), quando rodo a suíte, então o comportamento do corredor 1×N permanece coberto e verde.",
    ],
    requirementKeys: ["RNF-181"],
    priority: "highest",
    storyPoints: 3,
    status: "done",
    assignee: null,
  },
];
