import type { IUserStory } from "../types.ts";

export const stories: IUserStory[] = [
  {
    key: "US-069",
    asA: "jogador",
    iWant: "ver o nível sandbox listado na tela de seleção de níveis sempre desbloqueado",
    soThat: "possa acessar o espaço de prática antes de qualquer nível, independente do meu progresso na torre",
    acceptanceCriteria: [
      "Dado que o jogador abre a tela de seleção de níveis, quando a lista é renderizada, então o sandbox aparece como primeiro item.",
      "Dado que o jogador não completou nenhum nível da torre, quando a lista de seleção é exibida, então o sandbox aparece desbloqueado (sem cadeado).",
      "Dado que o jogador completou todos os níveis da torre, quando acessa a seleção, então o sandbox ainda aparece desbloqueado e selecionável.",
      "Dado que o jogador seleciona o sandbox na tela de seleção, quando confirma a escolha, então o jogo carrega o LevelData do sandbox (corredor curto, escada, sludge opcional).",
    ],
    requirementKeys: ["RF-001"],
    priority: "high",
    storyPoints: 2,
    status: "todo",
    assignee: null,
  },
  {
    key: "US-070",
    asA: "jogador",
    iWant: "jogar o nível sandbox com corredor curto, uma escada e um sludge opcional",
    soThat: "possa praticar walk!, feel e attack! sem pressão de pontuação",
    acceptanceCriteria: [
      "Dado que o jogador inicia o sandbox, quando o nível é carregado, então a arena exibe corredor horizontal de 3–5 tiles com escada ao final.",
      "Dado que o LevelData do sandbox inclui o sludge, quando o nível é renderizado, então um sludge fraco aparece no corredor.",
      "Dado que o jogador escreve código usando walk! e chega à escada, quando o turno é processado, então o sandbox é marcado como concluído.",
      "Dado que o sludge está presente e o jogador usa attack!, quando o turno é processado, então um único ataque elimina o sludge.",
      "Dado que o jogador usa o editor de código no sandbox, quando executa o código, então o motor de turnos e entidades se comportam identicamente aos demais níveis.",
    ],
    requirementKeys: ["RF-002", "RNF-001"],
    priority: "highest",
    storyPoints: 3,
    status: "todo",
    assignee: null,
  },
  {
    key: "US-071",
    asA: "jogador",
    iWant: "ver um texto de orientação curto e fixo na tela durante o sandbox",
    soThat: "saiba quais métodos usar para completar o nível introdutório",
    acceptanceCriteria: [
      "Dado que o sandbox está ativo e tem hint_text definido, quando o nível é carregado, então uma Label de orientação é exibida no HUD com o conteúdo do hint_text.",
      "Dado que o sandbox está ativo, quando o jogador avança turnos, então a Label de orientação permanece visível durante toda a duração do nível.",
      "Dado que um nível normal (is_sandbox=false) está ativo, quando o nível é carregado, então nenhuma Label de hint é exibida no HUD.",
    ],
    requirementKeys: ["RF-004"],
    priority: "high",
    storyPoints: 1,
    status: "todo",
    assignee: null,
  },
  {
    key: "US-072",
    asA: "jogador",
    iWant: "ser levado diretamente ao nível 1 ao concluir o sandbox, sem tela de resultado ou pontuação",
    soThat: "a transição seja fluida e eu saiba que o sandbox é apenas prática",
    acceptanceCriteria: [
      "Dado que o warrior sobe a escada no sandbox, quando o nível é concluído, então nenhuma ResultScreen é exibida.",
      "Dado que o sandbox é concluído, quando a transição ocorre, então a GameScreen carrega diretamente o nível 1 da beginner tower.",
      "Dado que o sandbox é concluído, quando o resultado é processado, então nenhum score (time bonus, rescue bonus, ace/clear bonus) é registrado ou exibido.",
      "Dado que o jogador completou o sandbox, quando verifica o score da torre, então o score acumulado não é alterado pela conclusão do sandbox.",
    ],
    requirementKeys: ["RF-003", "RF-005"],
    priority: "highest",
    storyPoints: 2,
    status: "todo",
    assignee: null,
  },
];
