import type { IUserStory } from "../types.ts";

export const stories: IUserStory[] = [
  {
    key: "US-001",
    asA: "desenvolvedor do domínio",
    iWant: "modelar o nível como uma grade imutável de espaços com unidades, posições e direções",
    soThat: "as regras de turno operem sobre um estado consultável e determinístico",
    acceptanceCriteria: [
      "Dado um LevelState, quando consulto o espaço numa posição/direção, então recebo um Space que responde empty?/stairs?/enemy?/captive?/wall? e o tipo da unidade.",
      "Dado um LevelState, quando aplico uma consulta, então o estado não é mutado (imutabilidade verificável em teste).",
    ],
    requirementKeys: ["RF-001", "RF-007"],
    priority: "highest",
    storyPoints: 5,
    status: "done",
    assignee: "usuario",
  },
  {
    key: "US-002",
    asA: "desenvolvedor do domínio",
    iWant: "um TurnResolver que aplique no máximo uma ação do warrior por turno de forma determinística",
    soThat: "o jogo respeite a regra nuclear de uma-ação-por-turno e seja testável/reproduzível",
    acceptanceCriteria: [
      "Dado um estado e uma ação, quando resolvo o turno, então obtenho sempre o mesmo próximo estado.",
      "Dado que o código registrou mais de uma ação, quando resolvo, então apenas a primeira é efetivada.",
      "Dado um método de resolução, quando o reviso, então ele faz uma só coisa (CQS), sem consultar-e-mutar no mesmo corpo.",
    ],
    requirementKeys: ["RF-002", "RF-003", "RNF-002"],
    priority: "highest",
    storyPoints: 8,
    status: "done",
    assignee: "usuario",
  },
  {
    key: "US-003",
    asA: "jogador",
    iWant: "que o nível termine em vitória ao alcançar a escada e em derrota ao zerar a saúde",
    soThat: "eu saiba claramente o desfecho da minha lógica",
    acceptanceCriteria: [
      "Dado o warrior na escada, quando o turno resolve, então o desfecho é vitória.",
      "Dado a saúde do warrior em 0, quando o turno resolve, então o desfecho é derrota.",
    ],
    requirementKeys: ["RF-004"],
    priority: "highest",
    storyPoints: 3,
    status: "done",
    assignee: "usuario",
  },
  {
    key: "US-004",
    asA: "jogador",
    iWant: "sentidos (feel/look/listen/health/direction_of_stairs/direction_of) sem efeito colateral",
    soThat: "minha lógica de turno decida a ação observando o ambiente sem gastar o turno",
    acceptanceCriteria: [
      "Dado um warrior, quando chamo qualquer sentido, então recebo o valor esperado e o turno NÃO é consumido.",
      "Dado um warrior, quando chamo look(direction), então recebo 3 espaços à frente na ordem do mais próximo ao mais distante.",
      "Dado um warrior, quando chamo listen e direction_of_stairs, então recebo os espaços com unidades e a direção que aponta para a escada.",
    ],
    requirementKeys: ["RF-005"],
    priority: "highest",
    storyPoints: 5,
    status: "done",
    assignee: "usuario",
  },
  {
    key: "US-005",
    asA: "jogador",
    iWant: "as ações walk!/attack!/rest! com direção e regeneração por descanso",
    soThat: "eu mova, lute corpo-a-corpo e me cure ao longo do nível",
    acceptanceCriteria: [
      "Dado feel.empty? à frente, quando walk!, então o warrior avança um espaço naquela direção.",
      "Dado um inimigo adjacente, quando attack!, então ele perde HP; atacar para trás causa dano reduzido.",
      "Dado o warrior abaixo do máximo, quando rest!, então a saúde sobe 10% do máximo sem ultrapassar o máximo.",
    ],
    requirementKeys: ["RF-006", "RF-010"],
    priority: "highest",
    storyPoints: 5,
    status: "done",
    assignee: "usuario",
  },
  {
    key: "US-006",
    asA: "jogador",
    iWant: "as ações rescue!/pivot!/shoot! com direção",
    soThat: "eu resgate cativos, vire o warrior e ataque à distância",
    acceptanceCriteria: [
      "Dado um cativo adjacente, quando rescue!, então o cativo é libertado e contabilizado.",
      "Dado o warrior, quando pivot!, então a direção dele é invertida sem ele se mover.",
      "Dado um alvo na linha de tiro, quando shoot!, então a primeira unidade até 3 espaços na direção perde HP.",
    ],
    requirementKeys: ["RF-006"],
    priority: "high",
    storyPoints: 5,
    status: "done",
    assignee: "usuario",
  },
  {
    key: "US-007",
    asA: "desenvolvedor do domínio",
    iWant: "as unidades (warrior/sludge/thick/archer/wizard/captive) com saúde e IA por polimorfismo",
    soThat: "cada inimigo aja conforme o original e o combate seja fiel",
    acceptanceCriteria: [
      "Dado um sludge/thick adjacente ao warrior, quando os inimigos reagem, então ele ataca corpo-a-corpo.",
      "Dado um archer/wizard dentro do alcance, quando reagem, então atacam à distância; cativo nunca ataca.",
      "Dado um tipo de unidade, quando reviso seu comportamento, então ele vive em sua própria classe (sem if-cadeia por tipo).",
    ],
    requirementKeys: ["RF-008", "RF-009"],
    priority: "highest",
    storyPoints: 8,
    status: "done",
    assignee: "usuario",
  },
  {
    key: "US-008",
    asA: "desenvolvedor da aplicação",
    iWant: "uma WarriorFacade que exponha só a API pública e isole o estado interno",
    soThat: "o código do jogador não leia nem mute o mundo diretamente",
    acceptanceCriteria: [
      "Dado a fachada, quando inspeciono sua superfície, então só existem os métodos de sentido e ação da API.",
      "Dado o código do jogador, quando tento acessar o mundo, então não há referência acessível a LevelState ou a outras unidades.",
      "Dado várias ações registradas no turno, quando resolvo, então a primeira vence e as demais são ignoradas.",
    ],
    requirementKeys: ["RF-011", "RNF-005"],
    priority: "highest",
    storyPoints: 5,
    status: "done",
    assignee: "usuario",
  },
  {
    key: "US-009",
    asA: "jogador",
    iWant: "escrever código GDScript (play_turn) executado em runtime com erros tratados",
    soThat: "eu controle o warrior como no Ruby Warrior sem travar o jogo ao errar",
    acceptanceCriteria: [
      "Dado um código válido com play_turn, quando o nível roda, então minha lógica é chamada a cada turno.",
      "Dado um erro de compilação/execução ou turno sem ação, quando o nível roda, então o jogo não trava e o warrior fica parado, com mensagem ao jogador.",
    ],
    requirementKeys: ["RF-011", "RF-012"],
    priority: "highest",
    storyPoints: 8,
    status: "done",
    assignee: "usuario",
  },
  {
    key: "US-010",
    asA: "desenvolvedor",
    iWant: "as definições declarativas dos 9 níveis e um LevelLoader que monte o estado inicial",
    soThat: "a beginner tower seja fiel ao original e fácil de ajustar",
    acceptanceCriteria: [
      "Dado o índice de um nível, quando carrego, então o LevelState inicial reflete o layout, unidades, escada e direção do original.",
      "Dado um nível, quando inspeciono sua definição, então ela declara descrição, habilidades introduzidas, time bonus e ace score na ordem canônica (L1..L9).",
    ],
    requirementKeys: ["RF-014", "RF-015"],
    priority: "highest",
    storyPoints: 8,
    status: "done",
    assignee: "usuario",
  },
  {
    key: "US-011",
    asA: "desenvolvedor",
    iWant: "uma solução-referência (play_turn) para cada um dos 9 níveis",
    soThat: "eu demonstre o jogo e valide paridade ponta-a-ponta",
    acceptanceCriteria: [
      "Dado o nível N e sua solução-referência, quando executada, então o nível é vencido.",
      "Dado a solução de um nível, quando a reviso, então ela nunca ataca cativos e usa apenas a API introduzida até aquele nível.",
    ],
    requirementKeys: ["RF-013"],
    priority: "medium",
    storyPoints: 5,
    status: "done",
    assignee: "usuario",
  },
  {
    key: "US-012",
    asA: "jogador",
    iWant: "ver minha pontuação com time bonus e saber se atingi o ace do nível",
    soThat: "eu tenha um objetivo de otimização além de só vencer",
    acceptanceCriteria: [
      "Dado o fim de um nível, quando calculo o score, então ele soma pontos por inimigos/resgates e o time bonus decrescente pelos turnos gastos.",
      "Dado o score e o ace score do nível, quando comparo, então o jogo sinaliza 'ace' se atingido ou superado.",
    ],
    requirementKeys: ["RF-016"],
    priority: "high",
    storyPoints: 5,
    status: "done",
    assignee: "usuario",
  },
  {
    key: "US-013",
    asA: "jogador",
    iWant: "ver a grade 2D top-down, as unidades e o feedback de cada turno, com HUD",
    soThat: "eu acompanhe visualmente o que minha lógica faz",
    acceptanceCriteria: [
      "Dado um turno resolvido, quando os eventos chegam à apresentação, então movimento/ataque/dano/descanso/resgate/tiro são exibidos.",
      "Dado um nível em andamento, quando observo a tela, então o HUD mostra saúde, número do turno, descrição do nível e pontuação.",
      "Dado os sprites do jogo, quando os inspeciono, então são placeholders com pontos de troca documentados para a arte da 42.",
    ],
    requirementKeys: ["RF-017"],
    priority: "high",
    storyPoints: 8,
    status: "backlog",
    assignee: "usuario",
  },
  {
    key: "US-014",
    asA: "jogador",
    iWant: "menu inicial, telas de transição da torre, avanço/reinício, resultado, créditos e progresso salvo",
    soThat: "eu jogue a torre completa do começo ao fim",
    acceptanceCriteria: [
      "Dado o menu, quando inicio, então começo no nível correto conforme meu progresso salvo.",
      "Dado vencer um nível, quando ele termina, então vejo a tela de resultado e avanço ao próximo, podendo reiniciar um nível.",
      "Dado concluir a torre, quando o último nível termina, então vejo os créditos e o progresso persiste entre sessões (user://).",
    ],
    requirementKeys: ["RF-018"],
    priority: "high",
    storyPoints: 8,
    status: "backlog",
    assignee: "usuario",
  },
  {
    key: "US-015",
    asA: "jogador",
    iWant: "efeitos sonoros e trilha durante o jogo",
    soThat: "a experiência seja mais imersiva e polida para a jam",
    acceptanceCriteria: [
      "Dado um evento de turno (andar/atacar/dano/descansar/resgatar/atirar/vitória/derrota), quando ele ocorre, então o SFX correspondente toca.",
      "Dado o jogo em andamento, quando jogo, então há trilha de fundo com controle de volume básico.",
    ],
    requirementKeys: ["RF-019"],
    priority: "medium",
    storyPoints: 5,
    status: "backlog",
    assignee: "usuario",
  },
  {
    key: "US-016",
    asA: "desenvolvedor",
    iWant: "garantir Clean Architecture, testes de domínio e estilo verificados mecanicamente",
    soThat: "o código atenda aos princípios do projeto e fique livre de regressão",
    acceptanceCriteria: [
      "Dado o Domain/Application, quando verifico, então não há 'extends Node' nem dependência para fora (grep/lint limpos).",
      "Dado as regras de domínio, quando rodo os testes, então 100% têm teste GUT determinístico verde.",
      "Dado o projeto, quando rodo as checagens, então gdformat não reporta diffs e gdlint reporta 0 violações.",
    ],
    requirementKeys: ["RNF-001", "RNF-003", "RNF-004"],
    priority: "high",
    storyPoints: 5,
    status: "done",
    assignee: "usuario",
  },
];
