import type { IUserStory } from "../types.ts";

export const stories: IUserStory[] = [
  // ── FUNDAÇÕES (P0, reutilizáveis, INDEPENDENTES entre si — paralelizáveis) ──
  {
    key: "US-160",
    asA: "Jogador",
    iWant:
      "ver os 4 personagens (herói, cadete, arqueiro/dev, diretora-chefe) animados conforme as ações do turno",
    soThat: "a arena ganhe vida fiel ao asset pack e eu leia o que cada entidade está fazendo",
    acceptanceCriteria: [
      "Dado um turno em que o herói anda ou fica parado, quando os turn_events são processados, então o AnimatedSprite2D do herói toca walk (ao andar) ou idle (parado), com os frames 48x48 do manifest.",
      "Dado um inimigo que ataca/atira/conjura, toma dano ou morre, quando o evento ocorre, então toca attack/shoot/cast, hurt ou death respectivamente, e o sprite é ancorado pelos pés na célula de 32px.",
    ],
    requirementKeys: ["RF-160", "RF-163", "RNF-160"],
    priority: "highest",
    storyPoints: 5,
    status: "done",
    assignee: null,
  },
  {
    key: "US-161",
    asA: "Jogador",
    iWant: "ver a arena renderizada com os tiles 32px do pack (chão/parede/escada), um personagem por célula",
    soThat: "o cenário seja fiel ao pack e a grade fique legível",
    acceptanceCriteria: [
      "Dado um nível carregado, quando a arena é renderizada, então o floor_layer mostra tile_floor/tile_wall/tile_stairs reais na grade nativa de 32px (TILE_SIZE=32, Nearest, escala inteira), sem reamostrar a arte.",
      "Dado o estado e as dimensões do nível, quando a arena monta, então cada célula mapeia para o tile correto e há um personagem por bloco, sem alterar a regra.",
    ],
    requirementKeys: ["RF-161", "RNF-160"],
    priority: "highest",
    storyPoints: 5,
    status: "done",
    assignee: null,
  },
  {
    key: "US-162",
    asA: "Jogador",
    iWant: "que os botões (Rodar/Resetar/Solução/Debug, menu e controles) tenham 4 estados visuais",
    soThat: "eu veja claramente o estado de cada controle ao interagir",
    acceptanceCriteria: [
      "Dado um botão, quando está em normal/hover/pressed/disabled, então mostra o estilo correspondente dos assets ui_* (borda ciano / preenchido+glow / escurecido / cinza), refletindo a interação real.",
      "Dado os controles existentes, quando migrados ao componente, então todos usam o mesmo sistema de 4 estados a partir da fonte data-driven única.",
    ],
    requirementKeys: ["RF-162"],
    priority: "highest",
    storyPoints: 3,
    status: "done",
    assignee: null,
  },
  {
    key: "US-172",
    asA: "Jogador",
    iWant:
      "que todas as telas sigam a identidade visual 42/glitch (paleta void, fontes e cores por contexto), não o tema default do Godot",
    soThat: "o jogo tenha a cara do design system desde a primeira tela, em vez de cinza/amarelo genérico",
    acceptanceCriteria: [
      "Dado o Theme global aplicado, quando qualquer tela renderiza, então usa o fundo void #0A0A0B (não cinza), as fontes Press Start 2P (títulos) + JetBrains Mono (resto) e as cores por contexto (zero amarelo base; verde sucesso / rubi perigo / ciano ativo), tudo data-driven via Theme.",
      "Dado o design system, quando uma tela renderiza, então há overlay de glitch (CanvasLayer Add/Screen) + fundo temático (tile_void/scanlines/data-rain) e os botões/sliders são tematizados (primário ciano), fechando o RNF-063 da 006.",
    ],
    requirementKeys: ["RF-165", "RF-163", "RNF-160"],
    priority: "highest",
    storyPoints: 5,
    status: "done",
    assignee: null,
  },
  // ── TELAS P0 (fluxo principal: jogo, menu, seleção) ──
  {
    key: "US-163",
    asA: "Jogador",
    iWant: "ver a tela de JOGO (arena) fiel ao mockup, reunindo status bar + arena + console + editor",
    soThat: "eu jogue na tela onde passo a maior parte do tempo, com a identidade visual completa",
    acceptanceCriteria: [
      "Dado a tela de jogo, quando renderizada, então mostra status bar terminal (LVL/HP/TURN/SCORE) no topo, a arena TileMap com um personagem animado por célula no centro e o console de turnos + controles embaixo, fiel ao mockup.",
      "Dado o editor de código retrátil na lateral, quando a tela abre, então ele começa visível e alterna pelo botão </>, com tipografia Press Start 2P/JetBrains Mono via Theme.",
    ],
    requirementKeys: ["RF-164", "RF-163", "RNF-160"],
    priority: "highest",
    storyPoints: 8,
    status: "todo",
    assignee: null,
  },
  {
    key: "US-164",
    asA: "Jogador",
    iWant: "ver o menu inicial fiel ao mockup (boot log + key art + opções)",
    soThat: "eu entre no jogo com a identidade glitch/42 desde a primeira tela",
    acceptanceCriteria: [
      "Dado o menu inicial, quando renderizado, então mostra fundo void + boot log fake ($ ./42warrior --boot, [WARN] corruption detected) + key_art.png + opções (Jogar/Continuar destacada ciano, Selecionar nível, Áudio, Sobre/Créditos), fiel ao mockup.",
      "Dado as opções do menu, quando exibidas, então usam o componente de botões 4-estados e a tipografia do Theme.",
    ],
    requirementKeys: ["RF-164", "RF-163", "RNF-160"],
    priority: "high",
    storyPoints: 5,
    status: "todo",
    assignee: null,
  },
  {
    key: "US-165",
    asA: "Jogador",
    iWant: "ver a tela de seleção de níveis fiel ao mockup (grade 3×3 com estados)",
    soThat: "eu escolha e refaça os andares já jogados",
    acceptanceCriteria: [
      "Dado a seleção de níveis, quando renderizada, então mostra a grade 3×3 dos 9 andares com estado (ui_check concluído, ui_star ace, ui_lock bloqueado), andar atual destacado ciano e andar 9 = chefe em magenta, fiel ao mockup.",
      "Dado os cartões de andar, quando exibidos, então usam os botões 4-estados e a tipografia do Theme.",
    ],
    requirementKeys: ["RF-164", "RF-163", "RNF-160"],
    priority: "high",
    storyPoints: 5,
    status: "todo",
    assignee: null,
  },
  // ── TELAS P1 (secundárias) ──
  {
    key: "US-166",
    asA: "Jogador",
    iWant: "ver a tela de resultado de nível (vitória E derrota) fiel ao mockup",
    soThat: "eu veja meu desempenho ao concluir um andar ou o motivo da derrota",
    acceptanceCriteria: [
      "Dado o fim de um andar com VITÓRIA, quando a tela de resultado renderiza, então mostra >> RUN COMPLETE, exit 0 em VERDE #00FF66, a grade (S/A/…) grande + estrelas (ui_star), stats alinhados (SCORE/TIME BONUS/TURNS/ACE) e botões PRÓXIMO/REPLAY, fiel ao mockup com a tipografia do Theme.",
      "Dado uma DERROTA, quando a tela renderiza, então mostra SIGKILL em RUBI #FF003C, efeito de morte (glitch/datamosh + screen-shake mínimo) e a opção de re-exec/retry, fiel ao mockup (sem amarelo).",
    ],
    requirementKeys: ["RF-164", "RF-163", "RNF-160"],
    priority: "medium",
    storyPoints: 3,
    status: "todo",
    assignee: null,
  },
  {
    key: "US-167",
    asA: "Jogador",
    iWant: "ver a transição de nível fiel ao mockup (card com glitch)",
    soThat: "eu entenda o contexto do próximo andar com a identidade glitch",
    acceptanceCriteria: [
      "Dado a passagem para um novo andar, quando a transição renderiza, então mostra o card central (/sys/memory/segment_NN, ANDAR NN com RGB split, descrição curta, badge de nova habilidade, prompt > ENTER), fiel ao mockup, com a tipografia do Theme.",
    ],
    requirementKeys: ["RF-164", "RF-163", "RNF-160"],
    priority: "medium",
    storyPoints: 3,
    status: "todo",
    assignee: null,
  },
  {
    key: "US-168",
    asA: "Jogador",
    iWant: "ver a tela de sandbox/tutorial fiel ao mockup (grade limpa)",
    soThat: "eu aprenda os comandos no onboarding sem corrupção visual",
    acceptanceCriteria: [
      "Dado o modo sandbox/tutorial, quando renderizado, então mostra a grade LIMPA (sem corrupção) com herói + portal, tooltips passo a passo e o badge MODO SANDBOX, fiel ao mockup, reusando a arena e a tipografia do Theme.",
    ],
    requirementKeys: ["RF-164", "RF-163", "RNF-160"],
    priority: "medium",
    storyPoints: 5,
    status: "todo",
    assignee: null,
  },
  {
    key: "US-169",
    asA: "Jogador",
    iWant: "ver a tela de glossário fiel ao mockup",
    soThat: "eu consulte os termos do jogo",
    acceptanceCriteria: [
      "Dado a tela de glossário, quando renderizada, então mostra a lista de termos (cadete, cativo, ace, turno, andar, corrupção, daemon) com definição, fiel ao mockup e com a tipografia do Theme.",
    ],
    requirementKeys: ["RF-164", "RF-163", "RNF-160"],
    priority: "medium",
    storyPoints: 2,
    status: "todo",
    assignee: null,
  },
  {
    key: "US-170",
    asA: "Jogador",
    iWant: "ver a tela de referência da API fiel ao mockup (man-page)",
    soThat: "eu consulte sentidos e ações ao escrever o código do warrior",
    acceptanceCriteria: [
      "Dado a tela de referência da API, quando renderizada, então mostra o painel man-page com SENTIDOS (feel/look/health/listen/direction_of_stairs) e AÇÕES (walk!/attack!/rest!/rescue!/pivot!/shoot!) e direção :forward/:backward, fiel ao mockup e com a tipografia do Theme.",
    ],
    requirementKeys: ["RF-164", "RF-163", "RNF-160"],
    priority: "medium",
    storyPoints: 3,
    status: "todo",
    assignee: null,
  },
  {
    key: "US-171",
    asA: "Jogador",
    iWant: "ver a tela de conclusão/créditos fiel ao mockup, com atribuição CORRETA",
    soThat: "eu tenha o fechamento da torre com a identidade do jogo e os créditos honestos",
    acceptanceCriteria: [
      "Dado a conclusão do jogo, quando a tela renderiza, então mostra o terminal SYSTEM RESTORED / exit 0 (verde) com os créditos rolando, fiel ao mockup e com a tipografia do Theme.",
      "CORREÇÃO FACTUAL (must-fix): Dado os créditos, quando exibidos, então NÃO contêm a linha falsa 'CC0 assets by freesound.org / opengameart.org' (arte e áudio são ORIGINAIS deste projeto) — em vez disso mostram 'Arte e áudio originais', MANTENDO 'Inspired by Ruby Warrior (Ryan Bates)' e 'Built with Godot 4 + GDScript'.",
    ],
    requirementKeys: ["RF-164", "RF-163", "RNF-160"],
    priority: "medium",
    storyPoints: 2,
    status: "todo",
    assignee: null,
  },
];
