import type { IUserStory } from "../types.ts";

export const stories: IUserStory[] = [
  // ── Bloco 1 — Matar a sobreposição / legibilidade (ScreenManager) ───────────────
  {
    key: "US-060",
    asA: "jogador",
    iWant: "que apareça apenas uma tela por vez, sem telas sobrepostas",
    soThat: "eu consiga ler e jogar a tela de jogo sem o bug de sobreposição",
    acceptanceCriteria: [
      "Dado qualquer transição de tela (menu→jogo→resultado→menu), quando a nova tela aparece, então existe exatamente 1 tela de topo visível e a anterior foi liberada (RF-060).",
      "Dado o código do jogo, quando se busca add_child de cenas de tela fora do ScreenManager, então o resultado é 0 ocorrências (RF-061).",
      "Dado um ciclo completo de telas, quando ele termina, então a contagem de telas de topo vivas volta ao baseline de 1, sem acúmulo de instâncias (RNF-062).",
    ],
    requirementKeys: ["RF-060", "RF-061", "RNF-062"],
    priority: "highest",
    storyPoints: 5,
    status: "done",
    assignee: null,
  },
  {
    key: "US-061",
    asA: "jogador",
    iWant: "a tela de jogo com a arena em destaque, HUD no topo e o console na faixa inferior",
    soThat: "eu foque na batalha e enxergue o estado do jogo sem poluição visual",
    acceptanceCriteria: [
      "Dado que abro a tela de jogo, quando ela monta, então a arena (corredor) é o maior elemento e nenhuma outra tela de topo a sobrepõe (RF-062).",
      "Dado a tela de jogo, quando observo topo e base, então vejo o HUD fixo (nível, HP em coração + valor, turno) no topo e a faixa do console embaixo (RF-062).",
    ],
    requirementKeys: ["RF-062"],
    priority: "highest",
    storyPoints: 3,
    status: "done",
    assignee: null,
  },
  // ── Bloco 2 — Salto visual (registro data-driven, sprites, tiles, animações) ─────
  {
    key: "US-062",
    asA: "mantenedor do jogo",
    iWant: "um registro central que mapeia entidade→sprite e (entidade, ação)→animação por caminho/ID",
    soThat: "eu troque ou adicione arte mexendo em um único ponto, sem editar scripts de cena",
    acceptanceCriteria: [
      "Dado o registro de assets, quando a cena precisa de um sprite/animação/tile, então ela o resolve via o registro e não há caminho de asset hardcoded em script de cena (RF-068).",
      "Dado que quero trocar o sprite de uma entidade, quando altero apenas o registro ou o arquivo por ele referenciado, então a troca reflete no jogo com 0 edições em scripts .gd de cena (RNF-060).",
    ],
    requirementKeys: ["RF-068", "RNF-060"],
    priority: "highest",
    storyPoints: 5,
    status: "done",
    assignee: null,
  },
  {
    key: "US-063",
    asA: "jogador",
    iWant: "sprites coesos e caprichados para as 7 entidades, inspirados no Ruby Warrior",
    soThat: "o jogo tenha identidade visual clara em vez de formas genéricas",
    acceptanceCriteria: [
      "Dado o jogo em execução, quando uma das 7 entidades (warrior, sludge, thick sludge, archer, wizard, captive, escada) aparece, então é desenhada por sprite do registro, sem forma geométrica procedural (RF-065).",
      "Dado os assets gráficos, quando carregados, então são arquivos de arte obtidos da internet, referenciados pelo registro e exibidos em execução (RF-069).",
    ],
    requirementKeys: ["RF-065", "RF-069"],
    priority: "highest",
    storyPoints: 5,
    status: "done",
    assignee: null,
  },
  {
    key: "US-064",
    asA: "jogador",
    iWant: "o corredor desenhado com tiles de masmorra coesos com a identidade visual",
    soThat: "o cenário pareça uma masmorra de verdade, não um fundo procedural",
    acceptanceCriteria: [
      "Dado um nível de largura N, quando o corredor é renderizado, então usa tiles (chão/parede/fundo) do registro e reflete o width do LevelState, sem render procedural por _draw (RF-066).",
    ],
    requirementKeys: ["RF-066"],
    priority: "high",
    storyPoints: 3,
    status: "done",
    assignee: null,
  },
  {
    key: "US-065",
    asA: "jogador",
    iWant: "ver animações de ataque, cura, defesa, andar, dano, resgate, tiro e morte a cada turno",
    soThat: "eu entenda visualmente o que acontece em cada turno da batalha",
    acceptanceCriteria: [
      "Dado um turno resolvido, quando a cena recebe os TurnEvents, então cada tipo (attacked, rested, pivoted, moved, took_damage, rescued, shot, died) dispara a animação correspondente na sprite da entidade afetada (RF-067).",
      "Dado os scripts de cena, quando inspecionados, então há 0 load/preload/new de classes de src/domain — o acesso ao estado se dá apenas pela camada Application (RNF-061).",
    ],
    requirementKeys: ["RF-067", "RNF-061"],
    priority: "highest",
    storyPoints: 5,
    status: "done",
    assignee: null,
  },
  // ── Bloco 3 — Imersão / polish (editor retrátil, console, Theme) ─────────────────
  {
    key: "US-066",
    asA: "jogador",
    iWant: "abrir e fechar o editor de código por um botão, sem trocar de tela",
    soThat: "eu edite o código imerso na batalha sem perder a arena nem o texto digitado",
    acceptanceCriteria: [
      "Dado a tela de jogo, quando aciono o botão '</> Código', então o editor desliza como overlay sobre a arena; ao fechar, a arena fica plena e o texto digitado é preservado (RF-063).",
    ],
    requirementKeys: ["RF-063"],
    priority: "high",
    storyPoints: 3,
    status: "done",
    assignee: null,
  },
  {
    key: "US-067",
    asA: "jogador",
    iWant: "controlar a reprodução dos turnos (play, pause, passo-a-passo, velocidade) e ver os eventos em ordem",
    soThat: "eu acompanhe e depure a execução do meu código no meu próprio ritmo",
    acceptanceCriteria: [
      "Dado o console de turnos, quando uso play, pause, passo-a-passo ou ajuste de velocidade, então o estado de reprodução muda conforme o controle e os turn_events são listados na ordem em que ocorreram (RF-064).",
    ],
    requirementKeys: ["RF-064"],
    priority: "high",
    storyPoints: 5,
    status: "done",
    assignee: null,
  },
  {
    key: "US-068",
    asA: "jogador",
    iWant: "uma aparência consistente entre todas as telas do jogo",
    soThat: "o jogo pareça um produto coeso e não peças desconexas",
    acceptanceCriteria: [
      "Dado as 5 telas (menu, jogo, transição, resultado, conclusão) e o HUD, quando renderizadas, então todas referenciam 1 mesmo Theme e há 0 cores/fontes avulsas hardcoded fora dele (RNF-063).",
    ],
    requirementKeys: ["RNF-063"],
    priority: "medium",
    storyPoints: 3,
    status: "done",
    assignee: null,
  },
];
