import type { IUserStory } from "../types.ts";

export const stories: IUserStory[] = [
  {
    key: "US-030",
    asA: "jogador",
    iWant: "ver e editar meu código do warrior num painel de código dentro do jogo",
    soThat: "eu escreva a lógica de turno sem sair do jogo",
    acceptanceCriteria: [
      "Dado um nível aberto, quando olho a tela, então há um painel CodeEdit editável com syntax highlight de GDScript, fonte monoespaçada e numeração de linhas.",
      "Dado o painel, quando digito, então o texto é editável e mantido enquanto o nível está aberto.",
    ],
    requirementKeys: ["RF-030", "RNF-032"],
    priority: "highest",
    storyPoints: 5,
    status: "done",
    assignee: "usuario",
  },
  {
    key: "US-031",
    asA: "jogador",
    iWant: "rodar o código que escrevi e ver o warrior executá-lo",
    soThat: "eu teste minha lógica de turno no nível",
    acceptanceCriteria: [
      "Dado um código com play_turn válido, quando clico Rodar, então o nível roda chamando minha lógica a cada turno via PlayerScriptRunner.",
      "Dado que cliquei Rodar de novo, quando a simulação reinicia, então ela usa o código atual do editor.",
      "Dado o editor, quando inspeciono seu acesso, então ele não referencia LevelState/unidades — só envia o texto ao runner (RNF-030).",
    ],
    requirementKeys: ["RF-031", "RNF-030"],
    priority: "highest",
    storyPoints: 5,
    status: "done",
    assignee: "usuario",
  },
  {
    key: "US-032",
    asA: "jogador",
    iWant: "resetar meu código ao esqueleto do nível e ver a solução de referência",
    soThat: "eu recomece do zero ou aprenda com a referência sem perder meu trabalho por acidente",
    acceptanceCriteria: [
      "Dado que cliquei Resetar e confirmei, quando o editor recarrega, então ele volta ao esqueleto inicial do nível.",
      "Dado que cliquei Ver solução, quando ela aparece, então é exibida em leitura sem sobrescrever silenciosamente meu código.",
    ],
    requirementKeys: ["RF-032", "RF-033"],
    priority: "medium",
    storyPoints: 3,
    status: "done",
    assignee: "usuario",
  },
  {
    key: "US-033",
    asA: "jogador",
    iWant: "que meu código seja salvo por nível entre sessões",
    soThat: "eu não perca minha lógica ao fechar o jogo",
    acceptanceCriteria: [
      "Dado que escrevi código num nível, quando saio e reabro o nível, então meu código é recarregado.",
      "Dado um nível sem código salvo, quando o abro, então ele aparece com o esqueleto inicial.",
      "Dado o save, quando verifico onde grava, então é em user:// e nunca em res:///repo (RNF-031).",
    ],
    requirementKeys: ["RF-034", "RNF-031"],
    priority: "high",
    storyPoints: 5,
    status: "done",
    assignee: "usuario",
  },
  {
    key: "US-034",
    asA: "jogador",
    iWant: "ver mensagens claras quando meu código falha",
    soThat: "eu corrija erros sem o jogo travar",
    acceptanceCriteria: [
      "Dado um erro de compilação, quando clico Rodar, então vejo a mensagem (e a linha quando disponível) num painel junto ao editor e o jogo não trava.",
      "Dado um código que lança exceção em runtime num turno, quando o turno roda, então a exceção é exibida e a simulação não quebra o jogo.",
    ],
    requirementKeys: ["RF-035"],
    priority: "highest",
    storyPoints: 5,
    status: "done",
    assignee: "usuario",
  },
  {
    key: "US-035",
    asA: "jogador",
    iWant: "um esqueleto inicial por nível com as habilidades disponíveis",
    soThat: "eu saiba por onde começar a programar em cada nível",
    acceptanceCriteria: [
      "Dado um nível novo, quando abro o editor, então há a assinatura play_turn(warrior) e um comentário listando as habilidades/sentidos disponíveis até aquele nível.",
    ],
    requirementKeys: ["RF-036"],
    priority: "high",
    storyPoints: 3,
    status: "done",
    assignee: "usuario",
  },
];
